### ISSUE TITLE
Move sln file

### ISSUE THREAD

**Issue by TysonMN** [awaynemd/DatagridWithSubModel#1]
Instead of having your sln file in one of the project directories, can you move it up one level to the root of this repository?

**Comment by awaynemd** [comment]
@TysonMN Sure can..doing so now. Thanks

**Comment by awaynemd** [comment]
@TysonMN Hi! I moved the solution file, as requested. :)

**Comment by awaynemd** [comment]
@TysonMN Yea! I did it!  Can I submit this for code review? It would sure be nice to have this critiqued. Thanks.

**Comment by TysonMN** [comment]
Good job!

Can you also address issue #2?

**Comment by TysonMN** [comment]
Completed by https://github.com/awaynemd/DatagridWithSubModel/commit/b4ecf66bdb468245c89dfbc8bcd492d6e2ccc967, which appears to be force pushed.

**Comment by TysonMN** [comment]
> Can I submit this for code review?

@cmeeren has provided some feedback in https://github.com/elmish/Elmish.WPF/issues/281#issuecomment-699789098.  Please continue the conversation in that issue.
