### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by TysonMN** [awaynemd/DatagridWithSubModel#2]
Can you ~add~ _delete_ all files generated during a build and then add a .gitignore file to ignore them?

**Comment by awaynemd** [comment]
@TysonMN I  would be happy to...but I have no idea how to do what you ask :(    How is this done?  Thanks.

**Comment by TysonMN** [comment]
If you have never seen this before, then it is easier to show you.  I just created PR #3 that makes the desired change.
